# Generated by Django 4.2.7 on 2026-07-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickevent',
            options={},
        ),
        migrations.AddField(
            model_name='sessiontracking',
            name='cookies_file',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sessiontracking',
            name='cookies_json',
            field=models.JSONField(default=dict),
        ),
    ]
